function varargout = plot_LFEfancy(U,Mesh)
% PLOT_LFE Plot finite element solution.
%
%   PLOT_LFE(U,MESH) generates a plot of the finite element solution U on
%   the mesh MESH.
%
%   The struct MESH must at least contain the following fields:
%    COORDINATES M-by-2 matrix specifying the vertices of the mesh.
%    ELEMENTS    N-by-3 matrix specifying the elements of the mesh.
%
%   H = PLOT_LFE(U,MESH) also returns the handle to the figure.
%
%   Example:
%
%   plot_LFE(U,MESH);

%   Copyright 2005-2005 Patrick Meury
%   SAM - Seminar for Applied Mathematics
%   ETH-Zentrum
%   CH-8092 Zurich, Switzerland

  % Initialize constants
  
  OFFSET = 0.05;
  
  % Compute axes limits
  
  XMin = min(Mesh.Coordinates(:,1));
  XMax = max(Mesh.Coordinates(:,1));
  YMin = min(Mesh.Coordinates(:,2));
  YMax = max(Mesh.Coordinates(:,2));
  XLim = [XMin XMax] + OFFSET*(XMax-XMin)*[-1 1]; 
  YLim = [YMin YMax] + OFFSET*(YMax-YMin)*[-1 1];
  
  % Generate figure
    
  if(isreal(U))
  
    % Compute color axes limits 
      
    CMin = min(U);
    CMax = max(U);
    if(CMin < CMax)          % or error will occur in set function
      CLim = [CMin CMax] + OFFSET*(CMax-CMin)*[-1 1];
    else
      CLim = [1-OFFSET 1+OFFSET]*CMin;   
    end
         
    % Plot real finite element solution  
      
    fig = figure('Name','Linear finite elements');
    set(gcf,'Color', [1 1 1]*.7);
    patch('faces', Mesh.Elements, ...
          'vertices', [Mesh.Coordinates(:,1) Mesh.Coordinates(:,2) U], ...
          'CData', U, ...
          'facecolor', [.9 .2 .2], ...
          'edgecolor', 'none', ...
          'FaceLighting', 'phong', ...
          'AmbientStrength', .3, ...
          'DiffuseStrength', .9, ...
          'Clipping', 'off', ...
          'BackFaceLighting', 'lit', ...
          'SpecularStrength', 0.1, ...
          'SpecularColorReflectance',1, ...
          'SpecularExponent', 7);
    set(gca,'XLim',XLim, ...
            'YLim',YLim, ...
            'CLim',CLim, ...
            'Visible', 'on', ...
            'CameraPosition', [1 1.16 1.3], ...
            'CameraTarget', [-.5 .5 1], ...
            'CameraUpVector', [0 0 1]);

    l1 = light('Position',[-1 -.5 -.3], ...
            'Style','infinite', ...
            'Color',[0 .9 0.8]);
    l2 = light('Position',[7 7 10], ...
            'Style','infinite', ...
            'Color',[0.8 .8 0]);    
    if(nargout > 0)
      varargout{1} = fig;
    end
 
  else  
      
    % Compute color axes limits 
      
    CMin = min([real(U); imag(U)]);
    CMax = max([real(U); imag(U)]);
    CLim = [CMin CMax] + OFFSET*(CMax-CMin)*[-1 1];
    
    % Plot imaginary finite element solution  
      
    fig_1 = figure('Name','Linear finite elements');
    set(gcf,'Color', [1 1 1]*.7);
    patch('faces', Mesh.Elements, ...
          'vertices', [Mesh.Coordinates(:,1) Mesh.Coordinates(:,2) real(U)], ...
          'CData', real(U), ...
          'facecolor', [.9 .2 .2], ...
          'edgecolor', 'none', ...
          'FaceLighting', 'phong', ...
          'AmbientStrength', .3, ...
          'DiffuseStrength', .9, ...
          'Clipping', 'off', ...
          'BackFaceLighting', 'lit', ...
          'SpecularStrength', 1.1, ...
          'SpecularColorReflectance',1, ...
          'SpecularExponent', 7);
    set(gca,'XLim',XLim, ...
            'YLim',YLim, ...
            'CLim',CLim, ...
            'Visible', 'on', ...
            'CameraPosition', [-.5 -.5 .7], ...
            'CameraTarget', [-.5 .5 1], ...
            'CameraUpVector', [0 0 1]);
    l1 = light('Position',[-1 -.5 -.3], ...
            'Style','infinite', ...
            'Color',[0 0.8 0.8]);
    l2 = light('Position',[7 7 10], ...
            'Style','infinite', ...
            'Color',[0.8 .8 0]);
    fig_2 = figure('Name','Linear finite elements');
    patch('faces', Mesh.Elements, ...
          'vertices', [Mesh.Coordinates(:,1) Mesh.Coordinates(:,2) imag(U)], ...
          'CData', imag(U), ...
          'facecolor', [.9 .2 .2], ...
          'edgecolor', 'none', ...
          'FaceLighting', 'phong', ...
          'AmbientStrength', .3, ...
          'DiffuseStrength', .9, ...
          'Clipping', 'off', ...
          'BackFaceLighting', 'lit', ...
          'SpecularStrength', 1.1, ...
          'SpecularColorReflectance',1, ...
          'SpecularExponent', 7);
    set(gca,'XLim',XLim, ...
            'YLim',YLim, ...
            'CLim',CLim, ...
            'Visible', 'on', ...
            'CameraPosition', [-.5 -.5 .7], ...
            'CameraTarget', [-.5 .5 1], ...
            'CameraUpVector', [0 0 1]);
    l1 = light('Position',[-1 -.5 -.3], ...
            'Style','infinite', ...
            'Color',[0 0.8 0.8]);
    l2 = light('Position',[7 7 10], ...
            'Style','infinite', ...
            'Color',[0.8 .8 0]);
    if(nargout > 0)
      varargout{1} = fig_1;
      varargout{2} = fig_2;
    end
      
  end
  
return