%SaveResults	Save results struct to file
%
%This saves results as returned by MergeResults, ReorderResults etc. in
%the format RunTests saves data.
%
%usage : SaveResults(FileName,R)
%
%FileName = Name of the file to save in, .mat is appendend if it's 
%           not already there.
%R        = Restults struct as generated by MergeResults or loaded 
%           with R=load('Results.mat')



%% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
%% These programs were prepared by the Regents of the University of
%% California at Los Alamos National Laboratory (the University) under
%% contract W-7405-ENG-36 with the U.S. Department of Energy (DOE) and
%% under Contract KC-07-01-01 with the Department of Energy(DOE),
%% Office of Science, Mathematical, Information, and Computational Sciences,
%% Applied Mathematical Sciences Program.  All rights in these programs
%% are reserved by the DOE and the University.

%% Permission is granted to the public to copy and use this software
%% without charge, provided that this Notice and the statements of 
%% authorship are reproduced on all copies. Neither the U.S. government 
%% nor the University makes any warranty, express or implied, or assumes 
%% any liability or responsibility for the use of this software.

%% AMG code written by Menno Verbeek, in collaboration with Jane Cullum
%%  and Wayne Joubert.
%% %%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%


function SaveResults(SaveResults7493057WeirdName,SaveResults7493057WeirdData)

getstruct(SaveResults7493057WeirdData)
clear SaveResults7493057WeirdData

eval(['clear SaveResults7493057WeirdName; save ',SaveResults7493057WeirdName])
